// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN6ORvxH6ENNtlBNtG4WF0W4vdNsMk_1g',
    appId: '1:306180711185:web:f068a7c517975108c562b0',
    messagingSenderId: '306180711185',
    projectId: 'tic-tac-toe-remaster',
    authDomain: 'tic-tac-toe-remaster.firebaseapp.com',
    storageBucket: 'tic-tac-toe-remaster.appspot.com',
    measurementId: 'G-WRF430N8QB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT89sF1Gt3VQPrju8vw3V2ZFxXe-7dhGI',
    appId: '1:306180711185:android:b8b3189ade9d660dc562b0',
    messagingSenderId: '306180711185',
    projectId: 'tic-tac-toe-remaster',
    storageBucket: 'tic-tac-toe-remaster.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB59liG5OmREy7iv4hnPVRAdM9fhYjRnUw',
    appId: '1:306180711185:ios:b6ec1678004bff86c562b0',
    messagingSenderId: '306180711185',
    projectId: 'tic-tac-toe-remaster',
    storageBucket: 'tic-tac-toe-remaster.appspot.com',
    iosBundleId: 'com.example.tictactoe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB59liG5OmREy7iv4hnPVRAdM9fhYjRnUw',
    appId: '1:306180711185:ios:b6ec1678004bff86c562b0',
    messagingSenderId: '306180711185',
    projectId: 'tic-tac-toe-remaster',
    storageBucket: 'tic-tac-toe-remaster.appspot.com',
    iosBundleId: 'com.example.tictactoe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCN6ORvxH6ENNtlBNtG4WF0W4vdNsMk_1g',
    appId: '1:306180711185:web:a27d319bf65e599bc562b0',
    messagingSenderId: '306180711185',
    projectId: 'tic-tac-toe-remaster',
    authDomain: 'tic-tac-toe-remaster.firebaseapp.com',
    storageBucket: 'tic-tac-toe-remaster.appspot.com',
    measurementId: 'G-V6K3NWS31E',
  );
}
